version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: c:\build
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: $(Major).$(Minor).$(Build).{build}
  assembly_file_version: $(Major).$(Minor).$(Build).{build}
  assembly_informational_version: $(Major).$(Minor).$(Build).{build}
environment:
  Major:
    secure: jHuXsuGiVQokAbKMuQbQnA==
  Minor:
    secure: jHuXsuGiVQokAbKMuQbQnA==
  Build:
    secure: n9Ivv6IDHEqUTnwSpJiHPg==
build:
  verbosity: minimal
test: off
artifacts:
- path: '**\bin\$(configuration)\*.exe'
  name: Build
deploy: off