version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
clone_folder: c:\build
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}.{build}'
  assembly_file_version: '{version}.{build}'
  assembly_informational_version: '{version}.{build}'
build:
  verbosity: minimal
test: off
artifacts:
- path: DNF-Gold/bin/Release/金币比价器.exe
  name: 金币比价器
deploy: off